# Generated by Django 4.1 on 2022-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'Universal Coordinated Time'), ('PST', 'Pakistan Standard Time')], default='UTC', max_length=3),
        ),
    ]
